@host = http://localhost:8080/api/v1
@password = e4e6eff0-a608-41e2-802e-83fb71757462
@token = eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiQURNSU4iLCJzdWIiOiJqb2huQGdtYWlsLmNvbSIsImlhdCI6MTcyODM0NzkzNSwiZXhwIjoxNzI4MzUxNTM1fQ.6meyrp8uEAc6ML5p1HC_f0CKzqVUEo6kalR_mffnoEM

# AUTHENTICATION

# Register user
POST {{host}}/auth/register  HTTP/1.1
Content-Type: application/json

{
  "fullname": "John",
  "email": "john@gmail.com",
  "password": "John12345*",
  "role": "ADMIN"
}

### 

# Log in user
POST {{host}}/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "john@gmail.com",
  "password": "John12345*"
}


### -***********************************************-

# PALETS

# Create a pallet
POST {{host}}/pallets HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "maxWeight": 5.0,
  "location": "Warehouse B"
}

###

# Get all pallets
GET {{host}}/pallets HTTP/1.1
Authorization: Bearer {{token}}


### -***********************************************-

# LOADS